### PR TITLE
Maven cleanup

### PR DESCRIPTION
**Pull request by Sanne**
please see commit messages for details

### CODE REVIEW

**Comment by Sanne** [comment]
Hurray, first pull request!

**Comment by emmanuelbernard** [comment]
I've got an error

[ERROR] Failed to execute goal on project hibernate-ogm-core: Could not resolve dependencies for project org.hibernate.ogm:hibernate-ogm-core:jar:3.0.0-SNAPSHOT: Could not find artifact javassist:javassist:jar:3.12.1.GA} in jboss-public-repository-group (http://repository.jboss.org/nexus/content/groups/public/) -> [Help 1]

**Comment by Sanne** [comment]
weird, works for me and it seems to properly exist:
http://repository.jboss.org/nexus/content/groups/public/javassist/javassist/3.12.1.GA/

you can downgrade that one, shouldn't do any harm.
you're not running it offline?

**Comment by Sanne** [comment]
(by downgrade I mean keeping the same version you already had)

**Comment by emmanuelbernard** [comment]
This one looks applied already

**Pull request closed without merging**
